model_name: mobilenetv3_1d
num_classes: 6

kernel_size_list: [3, 5, 7]
expand_ratio_list: [0.5, 1, 3, 4, 6]
depth_list: [1, 2, 3, 4]
width_mult: 0.25
input_seq_len: 23
patch_size: 1
feature_cross: false
arch: "Patchemb"
act_func_list: ["h_swish","h_swish","relu6"]



Task: "full"
NSGA: False
checkpoint_path: None
work_path: "nsga_output/OFA_D4K7E6W64_10x"

runtime:
  n_epochs: 64
  batch_size: 2048
  num_workers: 3

  opt_type: "sgd"
  init_lr: 0.1
  momentum: 0.99
  no_nesterov: False
  lr_schedule_type: "cosine"
  weight_decay: 3e-5
  no_decay_keys: "bn#bias"
  warmup_epochs: 5
  warmup_lr: 0.000001
  
  model_init: "he_fout"
  label_smoothing: 0
  validation_frequency: 1
  dynamic_batch_size: 2







